version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: credence-postgres
    environment:
      POSTGRES_USER: credence
      POSTGRES_PASSWORD: credence
      POSTGRES_DB: credence
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U credence"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: {}


